- name: configure vlan db on aristas
  hosts: "{{ stat_host }}"
  gather_facts: false
  vars:
  tasks:
#  - name: pull in config file
#    ansible.builtin.include_vars:
#      file: "configs/{{ inventory_hostname }}-vlandb.yml"

#  - name: set vlans based on file settings
#    arista.eos.eos_vlans:
#      config:
#      - vlan_id: "{{ item.vid }}"
#        name: "{{ item.vname }}"
#      state: overridden
#    loop: "{{ vlandb }}"

  - name: parse the vlandb config
    arista.eos.eos_vlans:
      running_config: "{{ lookup('file', 'configs/' + inventory_hostname + '-vlansdb') }}"
      state: parsed
    register: parsed_config

  - name: set vlans based on file settings
    arista.eos.eos_vlans:
      config: "{{ parsed_config.parsed }}"
      state: overridden

#  - name: push in the parsed config.  use block to do it all as a chunk
#    arista.eos.eos_config:
#      lines: "{{ parsed_config }}"
#      replace: block

  - name: save to startup config
    arista.eos.eos_command:
      commands: copy running-config startup-config